name: Release

on:
  push:
    tags:
      - 'v*'

env:
  # Rust build arguments
  BUILD_ARGS: "--release --all-features"
  # The binary name
  BIN_NAME: "vesshelm"
  # Docker token required to pull images from DockerHub
  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build:
    name: Build - ${{ matrix.platform.name }}
    # By default, runs on Ubuntu, otherwise, override with the desired os
    runs-on: ${{ matrix.platform.os || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        # Set platforms you want to build your binaries on
        platform:
          # Linux
            # The name is used for pretty print
          - name: Linux x86_64
            # The used Rust target architecture
            target: x86_64-unknown-linux-gnu
          - name: Linux aarch64
            target: aarch64-unknown-linux-gnu

          # Mac OS
          - name: MacOS x86_64
            target: x86_64-apple-darwin
          - name: MacOS aarch64
            target: aarch64-apple-darwin

          # Windows
          - name: Windows x86_64
            # Use another GitHub action OS
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v4

    # Linux & Windows
    - name: Install Rust toolchain
      if: ${{ !contains(matrix.platform.target, 'apple') }}
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ matrix.platform.target }}
        components: rustfmt, clippy
    - name: Build ${{ matrix.platform.name }} binary
      if: ${{ !contains(matrix.platform.target, 'apple') }}
      uses: actions-rs/cargo@v1
      # We use cross-rs if not running on x86_64 architecture on Linux
      with:
        command: build
        use-cross: ${{ !contains(matrix.platform.target, 'x86_64') }}
        args: ${{ env.BUILD_ARGS }} --target ${{ matrix.platform.target }}

    # Mac OS
    - name: Login to DockerHub
      if: contains(matrix.platform.target, 'apple')
      # We log on DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build ${{ matrix.platform.name }} binary
      if: contains(matrix.platform.target, 'apple')
      # We use a dedicated Rust image containing required Apple libraries to cross-compile on multiple archs
      run: |
        docker run --rm --volume "${PWD}":/root/src --workdir /root/src joseluisq/rust-linux-darwin-builder:2.0.0-beta.1 \
        sh -c "rustup target add ${{ matrix.platform.target }} && \
        if [ \"${{ matrix.platform.target }}\" = \"aarch64-apple-darwin\" ]; then \
          export CC=oa64-clang; \
          export CXX=oa64-clang++; \
        else \
          export CC=o64-clang; \
          export CXX=o64-clang++; \
        fi; \
        cargo build $BUILD_ARGS --target ${{ matrix.platform.target }}"

    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        # Finally, we store the binary as GitHub artifact for later usage
        name: ${{ matrix.platform.target }}-${{ env.BIN_NAME }}
        path: target/${{ matrix.platform.target }}/release/${{ env.BIN_NAME }}${{ contains(matrix.platform.target, 'windows') && '.exe' || '' }}
        retention-days: 1

  release:
    name: Release
    needs: [build]
    # We run the release job only if a tag starts with 'v' letter
    if: startsWith( github.ref, 'refs/tags/v' )
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Download all artifacts
    - uses: actions/download-artifact@v4
      with:
        path: artifacts

    # Goreleaser
    - name: Set up Go
      uses: actions/setup-go@v6
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        # Run goreleaser and ignore non-committed files (downloaded artifacts)
        args: release --clean --skip=validate
      env:
        # If you need homebrew to build a formula, you need to use a GitHub token
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_GORELEASER }}
